### ISSUE TITLE
is this still usable?

### ISSUE THREAD

**Issue by ldd** [hayesmaker/phase-2-e#1]
I haven't seen any activity in a while. Is this still usable?

**Comment by hayesmaker** [comment]
ye it's still usable with Phaser.js.. I'm currently planning to do some work to make this useful for other Canvas rendering frameworks.

**Comment by hayesmaker** [comment]
that might involve a new parent project called something else, which has adaptors for Phaser or Pixi, or MelonJS or your own custom game engine for example
